//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirtualAlejandro.Models
{
    using System;
    
    public enum Category : int
    {
        FrutosSecos = 0,
        Legumbres = 1,
        Cereales = 2,
        Verduras = 3,
        Frutas = 4,
        Condimentos = 5
    }
}
