//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirtualAlejandro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoAlmacen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductoAlmacen()
        {
            this.Precio = 0m;
            this.CantidadAlmacen = 0;
            this.CantidadCarrito = 0;
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Foto { get; set; }
        public decimal Precio { get; set; }
        public int CantidadAlmacen { get; set; }
        public int CantidadCarrito { get; set; }
        public Category Categoria { get; set; }
    }
}
